begin development
radsquad/listiq pull request #5
Opened 2017-02-28 17:18 UTC by akxcv

- Added yaspeller for markdown spellchecking.
- Moved HTML and CSS from `design` to `src`.
- Set up style compilation.
- Removed junk files.

In the future, we will enable `postcss-modules` and `react-css-modules`, as well as more advanced PostCSS and Webpack things.

2017-02-28 17:55 UTC, zacraven requested changes

2017-02-28 17:55 UTC, Ravenhiv commented on src/checklist.css
> +@import "partials/colors";
Может сразу подключим модуль postcss для нестинга а-ля sass? Чистый css без вложенности ужас неудобный.

2017-02-28 17:55 UTC, Ravenhiv commented on src/checklist.css
> +  color: black;
Скорее вопрос вкуса, но приоритетнее писать цвета хексом. #000

2017-02-28 17:55 UTC, Ravenhiv commented on src/checklist.html
> +  <main role="main" class="checklist-wrapper">
Есть ли смысл использовать role? Вопрос вообще про приложение в целом.

2017-02-28 17:55 UTC, Ravenhiv commented on src/index.css
> +  color: black;
аналогично, #000

2017-02-28 18:05 UTC, akxcv commented on src/checklist.css
> +@import "partials/colors";
У нас `precss`, там фичи а-ля sass прямо в `css` файлах.

2017-02-28 18:07 UTC, akxcv commented on src/checklist.html
> +  <main role="main" class="checklist-wrapper">
Да, HTML5 тэги типа `header`, `main` фоллбэкаются на обычные `div`, если в браузере нет поддержки. В таком случае теряется семантика, поэтому используют `role`. Во многом это связано с универсальным доступом (или как там accessibility по-русски называют)

2017-02-28 18:36 UTC, Ravenhiv commented on src/checklist.css
> +@import "partials/colors";
Круть.) А почему тогда не пишешь сразу со вложенностью?

2017-02-28 18:37 UTC, Ravenhiv commented on src/checklist.html
> +  <main role="main" class="checklist-wrapper">
А, тут умываю руки тогда. Не против, просто было интересно.

2017-02-28 18:38 UTC, akxcv commented on src/checklist.css
> +@import "partials/colors";
Пишу со вложенностью как раз)

2017-03-02 16:12 UTC, Ravenhiv commented on src/common.css
> +
Не ошибка, но нужно определиться - добавлять или нет пустые строки между вложенными селекторами. На работе, например, принято разделять пустыми строками только родительские селекторы, а те что с нестингом пишутся друг за другом, мне этот подход больше по душе, выглядит цельнее. Хотя раньше тоже разделял.)

2017-03-02 16:12 UTC, Ravenhiv commented on src/index.css
> +.title-input:focus {
а тут чего без нестинга? :)
&:focus {...}

2017-03-02 16:12 UTC, Ravenhiv commented on src/index.html
> +      <img class="logo" src="radsquad.svg" alt="radsquad logo" />
Тоже не ошибка. В HTML5 одиночные теги можно писать без закрывающей /. Хотя, учитывая, что все это будет переноситься в Реакт, тут оправданно.

2017-03-02 16:12 UTC, Ravenhiv commented on src/checklist.css
> +.item.done .title {
Тут тоже можно вложенность сделать. Для того, если вдруг потом появятся доп. стили для .item, чтобы не переписывать, а сразу была удобная форма записи.

2017-03-02 19:03 UTC, akxcv commented on .stylelintrc.json
> +    "rule-empty-line-before": null
вот хз как линтер нормально настроить :(
доку почитал, но как-то никак

2017-03-03 14:54 UTC, akxcv commented on .stylelintrc.json
> +        "ignore": "inside-block"
Это лучшее решение, что я нашел, не требующее всяких кастомных плагинов. Печально, что внутри блоков правило игнорируется (линтеру плевать, есть пустые строки или нет). Надо будет отдельно об этом потом подумать, сейчас пофигу.

2017-03-03 20:28 UTC, zacraven approved these changes

2017-03-03 20:28 UTC, Ravenhiv commented on src/checklist.css
> +.item.done {
Я бы тут тоже вложил, но пофиг. Если надо будет потом, то реализуем.)

2017-03-04 04:02 UTC, merged